/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Changelog: typeof import('./../components/Changelog.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Install: typeof import('./../components/install.vue')['default']
    OptionComponent: typeof import('./../components/OptionComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Update: typeof import('./../components/update.vue')['default']
    UrlDisplay: typeof import('./../components/UrlDisplay.vue')['default']
  }
}
